[package]
name = "shotgun"
description = "Minimal X screenshot utility"
version = "1.1.6"
authors = ["Dan Elkouby <streetwalkermc@gmail.com>"]
license = "MPL-2.0"
repository = "https://github.com/Streetwalrus/shotgun"
build = "build.rs"

[dependencies]
getopts = "0.2"
isatty = "0.1"
libc = "0.2"
time = "0.1"

[dependencies.image]
default-features = false
version = "0.19"
features = ["png_codec"]

[dependencies.x11]
version = "2.18"
features = ["xlib", "xrandr"]
