[package]
name = "shotgun"
version = "0.1.0"
authors = ["Dan Elkouby <streetwalkermc@gmail.com>"]

[dependencies]
getopts = "0.2"
image = "0.15"
isatty = "0.1"
libc = "0.2"
time = "0.1"

[dependencies.x11]
version = "2.15"
features = ["xlib"]
